### ISSUE TITLE
Chopping Car \ Paint Issue 

### ISSUE THREAD

**Issue by dougiebeatz** [renzuzu/renzu_projectcars#1]
I head over to the Chop Shop 1 , and i see nobody to talk to or a pop up UI to tell me anything . 

i have no errors in F8 or Console 

is this for cars that have been built or steal a car and chop ? 

Also When going to paint a projected car , i can click repaint , the color paint , then nothing happens if i walk away from the table i get frozen into place , No errors in f8 or console .

**Comment by renzuzu** [comment]
Watch the demo how to chop cars

About paint can you elaborate more probably with clip

Thanks
