### ISSUE TITLE
ehh

### ISSUE THREAD

**Issue by kingofkingzcd** [renzuzu/renzu_projectcars#11]
really wanted this to work. after downloading all dependencies and the main script the only part that somewhat works it the scrapping aspect and it is iffy more times than not. no other locations operate. interaction points just scuff and dont open any sort of menus etc. i guess the good part is it creates no errors either client side or server side. but still doesnt change the fact that its iffy at best.

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_projectcars/commit/fbc99cde191063b96b0a7ac13a338147b97a223f
