### ISSUE TITLE
Vehicle Parts Menu not continuing the purchase

### ISSUE THREAD

**Issue by congspeed** [renzuzu/renzu_projectcars#12]
Hi Renzu, Script works well especially the car building part. However, I cannot purchase any part so I just spawned them.

 The only problem that I have is if I try to buy a specific part from the auto shop, it doesn't continue after clicking the part that I want to buy. I can get out of being stuck if I press ESC.
![image](https://user-images.githubusercontent.com/95509405/144687957-a3749438-f622-4e0c-aa7c-149cf7b92266.png)

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_projectcars/commit/fbc99cde191063b96b0a7ac13a338147b97a223f
