### ISSUE TITLE
Register usableitem Sv_wrapper lua127

### ISSUE THREAD

**Issue by EdwinShima** [renzuzu/renzu_projectcars#17]
![unknown](https://user-images.githubusercontent.com/85160596/148866460-5bdb7e2b-15f8-44f8-938a-feea0ce36298.png)

**Comment by OupaKoos** [comment]
how can we fix that

**Comment by Jewsie** [comment]
I get the exact same issue, and I can't seem to figure out what exactly causes it. Well.. Almost

[script:renzu_project] SCRIPT ERROR: @renzu_projectcars/framework/sv_wrapper.lua:17: No such export GetSharedObject in resource qb-core
