### ISSUE TITLE
Car randomly turning

### ISSUE THREAD

**Issue by icecubepiso** [renzuzu/renzu_projectcars#2]
So.. i have a problem..
• using metadata (ox)

If i put a shell, in garage what you can rent.. the car just start turning around the garage.. like from the point where you put the shell after you move it then around that one imaginary dot on ground.

it moves like if you will try to rotate it..
and yeah sometimes some parts just not there.. like you install an door what you actually see it is there and then the doors remove it self..
(it's hard to describe :D... fidget spinner)

[Video](https://streamable.com/p2panm)

**Comment by renzuzu** [comment]
Its the collision issue
Try spawning it without it near on walls
Let me know

**Comment by icecubepiso** [comment]
Yeah, you were right.. if i put it in middle of garage it's ok..
So 1 last thing from me.. how do i change plate generating lmao
I tryed to find it.. but i think im too dumb to do that or idk if i get lost, but i want to different plate like.. need to be 4 to 4 you know (AAAA1111)

**Comment by renzuzu** [comment]
its in server.lua
find Genplate
