### ISSUE TITLE
project  cars items crashing inventory

### ISSUE THREAD

**Issue by Wackogaming** [renzuzu/renzu_projectcars#21]
So im using qb inventory and when adding the vehicle parts it is not giving the item in the inventory but when using all the paints it works but not with the parts ie doors,bonnet ect any help would be appreciated

**Comment by Zepherlah** [comment]
Im having the same issue sad times.

**Comment by Zepherlah** [comment]
> So im using qb inventory and when adding the vehicle parts it is not giving the item in the inventory but when using all the paints it works but not with the parts ie doors,bonnet ect any help would be appreciated

I figured it out, are you copying and pasting the item table from Rezu's list. Just double check cause it has a random "T" somewhere in the middle. should be able to spot it.

**Comment by Wackogaming** [comment]
That was the issue lol cheers

**Comment by Zepherlah** [comment]
Glad I could help let me know if you get it working! Mines still being a bish!

**Comment by Wackogaming** [comment]
Yeh that side is working just bits like when inside a private garage can’t put the mods back on the vehicle and putting imported cars don’t seem wrong want to load in pdm this is all todo with Renzu garages,customs and vehicle shop
