### ISSUE TITLE
Something is wrong for sure. QBCore help.

### ISSUE THREAD

**Issue by Zepherlah** [renzuzu/renzu_projectcars#23]
Little help cause im not sure, Items are in the QBCore shared items all good there, I can see the blips on the map.

I got it working for my ESX server fine, but my QBCore is frustrating

![image](https://user-images.githubusercontent.com/104341554/165037546-880c4dee-bbd7-400c-bbed-bea0cbbe4860.png)

![image](https://user-images.githubusercontent.com/104341554/165037490-13395300-474b-4645-8d3f-cdeed69355a5.png)

**Comment by Zepherlah** [comment]
Fixed the issue with the 195 error, I set the config to garage A when im using renzu garage in the SQL doh!

Still having an issue with the 3195 error.

**Comment by richiepleaserich** [comment]
Hey, you gotta change your sql from mysql to oxmysql. QBCore uses oxmysql.

**Comment by Zepherlah** [comment]
> Hey, you gotta change your sql from mysql to oxmysql. QBCore uses oxmysql.

I currently have it set to oxmysql, still same issue. Thanks for the reply though :(

**Comment by Zepherlah** [comment]
I think its something to do with my FX Version, cause I had the same issue with OkOk Chat I bought, I had to downgrade my chat for it to work and it was coming up with the same issue in the live console. some citizen scripting error.

**Comment by DeNtrlPredator** [comment]
@Zepherlah have you found out a fix for this?

**Comment by DeNtrlPredator** [comment]
@renzuzu are you able to provide support on this issue?
