### ISSUE TITLE
Project Car Double spawn and paint problem

### ISSUE THREAD

**Issue by mmle4** [renzuzu/renzu_projectcars#3]
Hi bro i am a friend of RKL, 

1. In the video there is many cars in the warehouse and it spawned in different places. On my server the car can only bbe spawned on the middle of the circle in the warehouse and it stacked if i create a new project.

2. having trouble with the paint 
also, ( the car cannot be painted, finished and driveable  ) 

im using linden at the moment. I admire your work and wouuld give u donation for this because me and RKL talked a lot abouut this feature so please help me :)

**Comment by renzuzu** [comment]
hi
1.
the demo video , (spawned many cars) is spawned by mine, using the create job in car builder menu

its just a little un document

you have to use numpad keys to move the vehicle, 
bydefault its spawned in the middle of circle.

2.

how are you using the paint item?

ex. paint_red

**Comment by mmle4** [comment]
Hi,

thanks, for the numpad it works but its really slow


for the item, all items for the car cannot be used

**Comment by renzuzu** [comment]
using linden_inv you have to register the item one by one..
you can ask RKL if you dont know how to, (i dont use linden_inv yet sorry)
full restart the server once the items is installed

i suggest moving to OX , its uses auto import of items from Database. which is easy and to save time.

**Comment by renzuzu** [comment]
also updated the script.

https://github.com/renzuzu/renzu_projectcars/commit/02d24b484439c9df39e5d575fe75127c273bc8c6

added GUI for guide.

SHIFT is to speed up the movement

**Comment by mmle4** [comment]
Hi bro, when i used the engine iteam for example does it automattically show the carrying engine animation? because when i used the engine nothing happened i sttand neear the car also

**Comment by renzuzu** [comment]
are you using meta inventory in config?
if no it should work without issues

if true , make sure the engine does have a meta data for current vehicle
```/giveitem 1 engine 1 blista```
