### ISSUE TITLE
Qb issue with vehicle keys

### ISSUE THREAD

**Issue by Wackogaming** [renzuzu/renzu_projectcars#30]
So been trying for about 3weeks now to figure this out on esx the keys work fine but on qb when finished building the car it says you you have the vehicle keys but it won't unlock the door same the the builder job and the lorry for delivering the cars no keys work can anyone help plz

**Comment by renzuzu** [comment]
it could be the plate issue. 
i have trimmed the plate when sending to keys in config.

**Comment by Wackogaming** [comment]
On esx there's no issue but on qb I've done everything possible and it just wont recognise any player as the key owner even though it tells you you have the keys it looks like a problem between the script and b vehicle keys when I take it out the script works love all your work by the way amazing 👍

**Comment by Wackogaming** [comment]
Also is there a fox for this lol

**Comment by Wackogaming** [comment]
Any fix for this Renzu ?

**Comment by renzuzu** [comment]
Use the latest main branch.. i just tested it with latest qb repo

Works fine.
Just add the right event
