### ISSUE TITLE
SharedObject console error prevents script from working

### ISSUE THREAD

**Issue by Jewsie** [renzuzu/renzu_projectcars#33]
Whenever I try to run the script, I get this console error. 

https://gyazo.com/d5d9f943633dba92abc97d448e40b9ab

I have tried making sure that oxmysql is running before qb-core and qb-core runs before anything else, I've also made sure in the config file that it's all setup as it should be, including putting certain things in the qb-core fxmanifest.lua such as

'client/cl_wrapper.lua',
'framework/cl_wrapper.lua'

'framework/sv_wrapper.lua',
'server/sv_wrapper.lua'

But nothing seems to work.

**Comment by renzuzu** [comment]
sounds your using very old version.

i have already updated the resource to use latest qbcore exports

**Comment by Jewsie** [comment]
I have the most updated QB and Script though, so that sounds pretty weird.
