### ISSUE TITLE
items

### ISSUE THREAD

**Issue by Kingpyro89** [renzuzu/renzu_projectcars#36]
i put the items in my lua and my city wont start all the way

**Comment by ChickenDipper1** [comment]
['door'] 				 	 = {['name'] = 'door', 			  	  		['label'] = 'Vehicle Door', 				['weight'] = 200, 		['type'] = 'item', 		['image'] = 'door.png',T 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Parts for Vehicle'},



Spot the typo, remove if and you will be fine  :)
