### ISSUE TITLE
might not be the right place sorry

### ISSUE THREAD

**Issue by Driftmonkey06** [renzuzu/renzu_projectcars#4]
Hi, im following your work since a long time and its pretty amazing, i wanted to make a request but i have no idea where to do it so i put it here cuz i know you ll see it, my request would be a livery editor, a little script that allow you to put a sticker on your car ( position, rotation and maybe scale ) something a little bit like Forza for example, i did a basic experimentation on my side i know that its possible, my system is just ugly and dont save ( but it work )

**Comment by renzuzu** [comment]
send me example video

**Comment by Driftmonkey06** [comment]
of my shitty experiment or of what i talk about ? ^^

**Comment by renzuzu** [comment]
yea, so i can get what the logic needs

**Comment by Driftmonkey06** [comment]
something similar to that for example : https://youtu.be/wWX32Iclrq4?t=305

**Comment by renzuzu** [comment]
Its not possible in gta logic imo

**Comment by Driftmonkey06** [comment]
it was made in SP : https://fr.gta5-mods.com/scripts/decal5
and i did it in FiveM but sticker was like an object so it was not really a part of the paint, i think the best chance is to check the link i sent

**Comment by renzuzu** [comment]
this not a vehicle livery anymore, its texture replace or kinda similar to Spray script graffiti you can find in cfx now.

i can implement it this way, but expect its not optimized, texture replacing need to be in loop specially if moving object like vehicle.

**Comment by Driftmonkey06** [comment]
well, if you are in, lets try it, i know that ton of people would love something like that
