### ISSUE TITLE
 Automotive Service Warehouse

### ISSUE THREAD

**Issue by Redphoenix604** [renzuzu/renzu_projectcars#44]
Upon pressing "E" to enter Automotive Service at the default garage set. I am teleported to what is supposed to be a Warehouse like in the Video Preview I'd assume.  "https://www.youtube.com/watch?v=XFTWhlUZrF0". 

But I am instead brought to an invisible area with minimal props. 
I can walk around as is there is a floor, and see the markers. 
But no "MLO"/Shell is appearing.

I am using Esx and I have zero "F8" errors, nor Console errors.

Preview: 
https://imgur.com/a/G2x3Fiz
https://imgur.com/a/w4Sq8FN

Thanks! Your work is amazing!

**Comment by renzuzu** [comment]
install bobipl 74
