### ISSUE TITLE
Unable to place Shell

### ISSUE THREAD

**Issue by HiTTA757** [renzuzu/renzu_projectcars#48]
hello, im having trouble placing shell down. i went to project car locations, still don't work. turned it off in config but still will not place shell down. using XO inventory

**Comment by HiTTA757** [comment]
![Uploading E6189B3C-454D-455D-83E5-5CE3340AD033.jpeg…]()

**Comment by renzuzu** [comment]
need more info, and picture is not uploaded

**Comment by HiTTA757** [comment]
![Uploading F5B20F6D-C5F6-434A-A1BA-992E3C842297.jpeg…]()

**Comment by HiTTA757** [comment]
![BB98C792-BEBF-4BD5-8A8B-12896E131E16](https://user-images.githubusercontent.com/127186414/226889977-7fa42177-ba91-4780-970e-c4de9dd88359.jpeg)

**Comment by renzuzu** [comment]
did you solved?

**Comment by HiTTA757** [comment]
yess

**Comment by Arootsy** [comment]
how did you slved?
