### ISSUE TITLE
Vehicle_shell not showing with use a item in inventory not errors

### ISSUE THREAD

**Issue by ajmedina** [renzuzu/renzu_projectcars#51]
I have instaled sql, items on ox_inventory and all dependencies not errors on console
I take the items but not work with use on inventory to place a trunk and start car crafting

onesyn enabled and test in console 
game cfx build v5.2.0 atop FXServer 6375

ingame GTAV Build +set sv_enforceGameBuild 2699
Can you help me is last script to server finished is a zombie apo dayz + rust building base etc.

**Comment by ajmedina** [comment]
sorry is a shell not work item to place on floor to car craft

**Comment by renzuzu** [comment]
vehicle_shell? those are meant to work for non meta data inventory only

**Comment by ajmedina** [comment]
I have the vehicle_shell object in my inventory but when I use it it doesn't do anything or let me put the project_car to start its creation, I don't get any errors in the console, 
Renzu thanx for all your good work if you need a host to your projects i have something 4 you

**Comment by ajmedina** [comment]
i use ox_inventory last version

**Comment by renzuzu** [comment]
hi ignore my last comment, its should be vehicle_blueprints is the one made for non meta inventory.

can you do step by step

buy Shell from junk shop.
buy the parts from auto parts (same brand and model for parts)

spawn shell
start placing bought auto parts.

tell me what model is the problem for trunk?

just take note you cannot spawn the auto parts (bonnet , trunk) from admin commands.
if you are using meta inventory enable in config.

**Comment by ajmedina** [comment]
[
![image](https://user-images.githubusercontent.com/35585935/232553356-c1e66ee1-6333-4895-be3c-9fdd82641283.png)
](url)
I've done all the steps as you told me and it's the same when I press use the blueprint_model object, it doesn't do anything or the console throws an error. It would be possible that the blueprints already appear in the city by zones and that with pieces the player repairs the cars like a gAYZ xd I have thought of this by implementing it in the zombie server
dependencies
oxmysql (2.6.0) 
ox_lib (3.1.4) 
ox_target (1.7.2) 
ox_inventory (2.27.0) 
es_extended (1.9.4)
Thanx

**Comment by renzuzu** [comment]
if the shell is not usable? a dumb question, is the item is registered in ox?
is the other item is usable like trunk,bonnet?

**Comment by ajmedina** [comment]
Sorry, it was my mistake, since I manually imported the files with the items.lua that came instead of ignoring it and letting it import automatically, I deleted the items and restarted and now it works, some lines change
Bad file manual import.
['vehicle_shell'] = {
     label = 'vehicle_shell',
     weight = 1,
     stack = true,
     close = true,
},
the double quote was the problem.
["vehicle_shell"] = {
label = "Vehicle_shell",
weight = 1,
stack = true,
close = true,
},
